version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: orio-chat-service-image
    container_name: orio-chat-service-container
    ports:
      - "8090:8090"
      - "8092:8092"
    depends_on:
      mysqldb:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/${MYSQL_DATABASE}
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
      - SPRING_SOCKET_IO_HOST=0.0.0.0
      - SPRING_SOCKET_IO_PORT=8092
    networks:
      - oriochat-springboot-mysql-network
  mysqldb:
    image: mysql:latest
    container_name: orio-chat-service-db-container
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - oriochat-springboot-mysql-data:/var/lib/mysql
    networks:
      - oriochat-springboot-mysql-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      retries: 10
      interval: 3s
      timeout: 30s
volumes:
  oriochat-springboot-mysql-data:
networks:
  oriochat-springboot-mysql-network:
    name: oriochat-springboot-mysql-network